# Generated by Django 3.1.7 on 2021-03-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.IntegerField()),
                ('title_english', models.CharField(max_length=255)),
                ('title_native', models.CharField(max_length=255)),
                ('title_romaji', models.CharField(max_length=255)),
                ('premiere', models.IntegerField()),
                ('premiere_precision', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('date', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('episodes', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('spoiler', models.BooleanField()),
                ('image_url', models.CharField(max_length=1024)),
                ('categories', models.ManyToManyField(to='backend.Category')),
                ('studios', models.ManyToManyField(to='backend.Studio')),
            ],
            options={
                'verbose_name': 'Тайтл',
                'verbose_name_plural': 'Тайтлы',
            },
        ),
        migrations.AddField(
            model_name='studio',
            name='titles',
            field=models.ManyToManyField(to='backend.Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='titles',
            field=models.ManyToManyField(to='backend.Title'),
        ),
    ]
