# Generated by Django 3.1.7 on 2021-03-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='episodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
