# Generated by Django 3.1.7 on 2021-03-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210306_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='title',
            name='studios',
        ),
        migrations.AddField(
            model_name='title',
            name='form',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='season',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='titles',
            field=models.ManyToManyField(related_name='categories', to='backend.Title'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='titles',
            field=models.ManyToManyField(related_name='studios', to='backend.Title'),
        ),
    ]
