# Generated by Django 3.1.7 on 2021-03-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210307_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_russian',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='title_russian',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
