# Generated by Django 3.1.7 on 2021-03-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210307_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_russian',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='form',
            field=models.CharField(default='tv', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='season',
            field=models.CharField(default='winter', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='title_russian',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
