# Generated by Django 3.1.7 on 2021-03-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210307_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description_russian',
            field=models.TextField(blank=True, null=True),
        ),
    ]
