# Generated by Django 3.1.7 on 2021-03-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_title_description_russian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=6)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'unique_together': {('season', 'year')},
            },
        ),
    ]
