# Generated by Django 3.1.7 on 2021-03-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Сезон', 'verbose_name_plural': 'Сезоны'},
        ),
        migrations.AddField(
            model_name='season',
            name='season_russian',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
