# Generated by Django 3.1.7 on 2021-03-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210307_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='season_russian',
        ),
    ]
