# Generated by Django 3.1.7 on 2021-03-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_season_season_russian'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('-year',), 'verbose_name': 'Сезон', 'verbose_name_plural': 'Сезоны'},
        ),
        migrations.AddField(
            model_name='season',
            name='season_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
