# Generated by Django 3.1.7 on 2021-03-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210307_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='season_index',
            new_name='month_ended',
        ),
        migrations.AddField(
            model_name='season',
            name='month_started',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
