# Generated by Django 3.1.7 on 2021-03-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210307_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='month_ended',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='month_started',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(),
        ),
    ]
