# Generated by Django 3.1.7 on 2021-03-07 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210307_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('-year', '-month_started'), 'verbose_name': 'Сезон', 'verbose_name_plural': 'Сезоны'},
        ),
    ]
