# Generated by Django 3.1.7 on 2021-03-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210307_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='season',
        ),
        migrations.RemoveField(
            model_name='title',
            name='year',
        ),
    ]
