# Generated by Django 3.1.7 on 2021-03-07 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210307_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.season'),
        ),
    ]
