# Generated by Django 3.1.7 on 2021-03-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_title_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
