# Generated by Django 3.1.7 on 2021-03-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20210307_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='data_id',
            field=models.IntegerField(unique=True),
        ),
    ]
