# Generated by Django 3.1.7 on 2021-03-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210312_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Anime',
        ),
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Аниме', 'verbose_name_plural': 'Аниме'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='titles',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='titles',
        ),
        migrations.AddField(
            model_name='category',
            name='anime',
            field=models.ManyToManyField(related_name='categories', to='backend.Anime'),
        ),
        migrations.AddField(
            model_name='studio',
            name='anime',
            field=models.ManyToManyField(related_name='studios', to='backend.Anime'),
        ),
    ]
