# Generated by Django 3.1.7 on 2021-03-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20210317_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='anime',
            new_name='anime_list',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='anime',
            new_name='anime_list',
        ),
    ]
